In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
customers = pd.read_csv("../database/customers.csv")
cards = pd.read_csv("../database/cards.csv")
merchants = pd.read_csv("../database/merchants.csv")

In [12]:
customers.head()

cards.head()

merchants.head()

   merchant_id   merchant_name       category       city country
0            1          PVR #1  Entertainment      Delhi   India
1            2  Water Board #2      Utilities  Hyderabad   India
2            3       Swiggy #3  Food Delivery      Noida   India
3            4  Vijay Sales #4    Electronics     Mumbai   India
4            5   Pantaloons #5        Fashion      Delhi   India

In [13]:
customers.head()

,customer_id,first_name,last_name,gender,age,city,state,occupation,annual_income,customer_segment,join_date
0,1,Oliver,Menon,Male,33,Chennai,Tamil Nadu,Student,488786,Standard,2021-02-03
1,2,Jai,Ganesh,Male,45,Jaipur,Rajasthan,Consultant,1264647,Standard,2025-05-13
2,3,Jagdish,Rattan,Male,56,Chandigarh,Chandigarh,Doctor,1687925,Standard,2021-09-06
3,4,Orinder,Bawa,Male,46,Hyderabad,Telangana,Consultant,2659593,Silver,2024-02-17
4,5,Ekaraj,Ray,Male,35,Pune,Maharashtra,Software Engineer,1686286,Standard,2024-12-29

In [ ]:
merchants.head()